version: '3.8'
services:

  grpc-server:
    build: ./
    container_name: grpc-server
    restart: always
    depends_on:
      - pg-server
    environment:
      GRPC_SERVER_ADDRESS: 0.0.0.0:8081
      POSTGRES_DSN: postgres://postgres:test@pg-server/rust
      RUST_LOG: info
    ports:
      - "8081:8081/tcp"

  pg-server:
    image: postgres:13.2-alpine
    container_name: pg-server
    restart: always
    environment:
      POSTGRES_DB: rust
      POSTGRES_PASSWORD: test
